language: node_js
node_js:
    - "6.9.1"
script: npm run karma-tests --single-run
addons:
    apt:
        sources:
            - google-chrome
        packages:
            - google-chrome-stable
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
install:
    - npm install
before_script:
    - npm run nodemon-client-server
    - npm run nodemon-api-server
    - npm run ui-tests
