language: node_js
node_js:
    - "6.9.1"
script: npm run ui-tests --single-run
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install
    - npm run build-client
    - npm run nodemon-client-server &
    - npm run nodemon-api-server &
    - /bin/sleep 10
notifications:
  email: false
dist: trusty
addons:
  chrome: stable
